"""add push registration

Revision ID: 06923c017fdf
Revises: 71954a3035b7
Create Date: 2023-06-20 11:29:26.047162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06923c017fdf'
down_revision = '71954a3035b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_sessions', sa.Column('push_registration', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_sessions', 'push_registration')
    # ### end Alembic commands ###
