"""add session cookie id

Revision ID: 32337a327dd5
Revises: 55c0792da973
Create Date: 2023-06-20 10:22:26.687076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32337a327dd5'
down_revision = '55c0792da973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('cookie_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'cookie_id')
    # ### end Alembic commands ###
