"""tracks need names

Revision ID: 5b74e76e44d5
Revises: 8c29aab57b65
Create Date: 2023-06-20 20:13:55.593091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b74e76e44d5'
down_revision = '8c29aab57b65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tunes', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tunes', 'name')
    # ### end Alembic commands ###
