"""add tunes

Revision ID: 6ef9b792cd48
Revises: 06923c017fdf
Create Date: 2023-06-20 20:07:24.156177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ef9b792cd48"
down_revision = "06923c017fdf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tunes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("spotify_id", sa.String(), nullable=False),
        sa.Column("album", sa.String(), nullable=False),
        sa.Column("primary_artist", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tunes")
    # ### end Alembic commands ###
