"""rework sessions

Revision ID: 71954a3035b7
Revises: 32337a327dd5
Create Date: 2023-06-20 11:00:08.106601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71954a3035b7"
down_revision = "32337a327dd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cookie_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("sessions")
    op.add_column(
        "users", sa.Column("refresh_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token")
    op.create_table(
        "sessions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "access_token", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "refresh_token", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expires_at", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "cookie_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="sessions_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="sessions_pkey"),
    )
    op.drop_table("login_sessions")
    # ### end Alembic commands ###
