"""add display name override

Revision ID: 8ededb5e2be3
Revises: 5b74e76e44d5
Create Date: 2023-06-21 22:31:08.679952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ededb5e2be3'
down_revision = '5b74e76e44d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('override_display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'override_display_name')
    # ### end Alembic commands ###
