"""add tunetime table

Revision ID: f0f5a7205a33
Revises: 8ededb5e2be3
Create Date: 2023-06-21 21:19:40.299219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0f5a7205a33"
down_revision = "8ededb5e2be3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tunetimes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "tunes", sa.Column("tunetime_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "tunes", "tunetimes", ["tunetime_id"], ["id"])

    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "login_sessions",
        sa.Column(
            "created_at", sa.Integer(), nullable=False, server_default="0"
        ),
    )

    op.alter_column("users", "created_at", server_default=None)
    op.alter_column("login_sessions", "created_at", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_constraint(None, "tunes", type_="foreignkey")
    op.drop_column("tunes", "tunetime_id")
    op.drop_column("login_sessions", "created_at")
    op.drop_table("tunetimes")
    # ### end Alembic commands ###
